apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-yoonjin2-kr-certificate
  namespace: gitlab
spec:
  secretName: gitlab-yoonjin2-kr-tls 
  duration: 2160h 
  renewBefore: 360h 
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer
  dnsNames:
    - gitlab.yoonjin2.kr 
