# letsencrypt-prod-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # This name should match the 'cert-manager.io/cluster-issuer' annotation in your Kroki Ingress.
spec:
  acme:
    # The ACME server URL for the Let's Encrypt production environment.
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address to register with the ACME server. Let's Encrypt uses this for important notices.
    email: gg582@naver.com # <--- IMPORTANT: REPLACE THIS WITH YOUR ACTUAL EMAIL ADDRESS
    # Name of a Kubernetes Secret to store the ACME account private key. Cert-Manager will create this.
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    # Define how Cert-Manager will solve challenges to prove domain ownership.
    solvers:
    - http01: # Use the HTTP-01 challenge type.
        ingress:
          class: nginx # This must match the 'ingressClassName' of your Ingress resource (e.g., Kroki Ingress).
                       # Ensure your NGINX Ingress Controller is handling this IngressClass.
