global:
  imageRegistry: ""
  imagePullSecrets: []

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonAnnotations: {}
commonLabels: {}
extraDeploy: []

replicaCount: 1

image:
  registry: docker.io
  repository: yuzutech/kroki
  tag: 0.28.0
  digest: ""
  pullPolicy: IfNotPresent

pdb:
  create: false
  minAvailable: 1
  maxUnavailable:

serviceAccount:
  create: true
  annotations: {}
  name:

deploymentAnnotations: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
priorityClassName:
runtimeClassName: ""
topologySpreadConstraints: []
securityContext: {}

containerPorts:
  http: 8000

livenessProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: false
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

service:
  annotations: {}
  type: ClusterIP
  clusterIP:
  sessionAffinity: None
  sessionAffinityConfig: {}
  loadBalancerIP:
  loadBalancerSourceRanges:
  externalTrafficPolicy: Cluster
  ports:
    http: 8000
  nodePorts:
    http:

ingress:
  enabled: true
  ingressClassName: nginx
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: gitlab.yoonjin2.kr
      paths:
        - /
  tls:
    - secretName: kroki-tls
      hosts:
        - gitlab.yoonjin2.kr

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

extraArgs: {}
extraEnvVars: []
extraEnvVarsCM:
extraEnvVarsSecret:

autoscaling:
  hpa:
    enabled: false
    minReplicas: ""
    maxReplicas: ""
    targetCPU: ""
    targetMemory: ""

bpmn:
  enabled: true
  image:
    registry: docker.io
    repository: yuzutech/kroki-bpmn
    tag: 0.28.0
    digest: ""
    pullPolicy: IfNotPresent
  securityContext: {}
  containerPorts:
    http: 8003
  resources: {}
  extraArgs: {}
  extraEnvVars: []
  extraEnvVarsCM:
  extraEnvVarsSecret:

diagramsnet:
  enabled: true
  image:
    registry: docker.io
    repository: yuzutech/kroki-diagramsnet
    tag: 0.28.0
    digest: ""
    pullPolicy: IfNotPresent
  securityContext: {}
  containerPorts:
    http: 8005
  resources: {}
  extraArgs: {}
  extraEnvVars: []
  extraEnvVarsCM:
  extraEnvVarsSecret:

excalidraw:
  enabled: true
  image:
    registry: docker.io
    repository: yuzutech/kroki-excalidraw
    tag: 0.28.0
    digest: ""
    pullPolicy: IfNotPresent
  securityContext: {}
  containerPorts:
    http: 8004
  resources: {}
  extraArgs: {}
  extraEnvVars: []
  extraEnvVarsCM:
  extraEnvVarsSecret:

mermaid:
  enabled: true
  image:
    registry: docker.io
    repository: yuzutech/kroki-mermaid
    tag: 0.28.0
    digest: ""
    pullPolicy: IfNotPresent
  securityContext: {}
  containerPorts:
    http: 8002
  resources: {}
  extraArgs: {}
  extraEnvVars: []
  extraEnvVarsCM:
  extraEnvVarsSecret:

tests:
  image:
    registry: ghcr.io
    repository: cowboysysop/pytest
    tag: 1.0.41
    digest: ""
    pullPolicy: IfNotPresent

