apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-gitlab-postgresql-0 
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi  # 사용하려는 용량
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"  # 사용자 정의 스토리지 클래스 (필요 시 조정)
  nodeAffinity:  # 특정 노드에 마운트
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - yjlee-900x5n
  hostPath:
    path: /etc/gitlab  # 노드의 경로
    type: DirectoryOrCreate  # 경로가 없으면 디렉토리를 생성

