apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitlab-postgresql-0 
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  
  storageClassName: "manual"  

