apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki-storageclass
provisioner: kubernetes.io/host-path
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  path: /var/lib/kubelet/volumes/loki-dynamic
