apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6","meta.helm.sh/release-name":"gitlab","meta.helm.sh/release-namespace":"gitlab"},"creationTimestamp":"2025-06-06T09:20:55Z","generation":6,"labels":{"app":"gitlab-gitlab-runner","app.kubernetes.io/managed-by":"Helm","chart":"gitlab-runner-0.74.1","heritage":"Helm","release":"gitlab"},"name":"gitlab-gitlab-runner","namespace":"gitlab","resourceVersion":"193743","uid":"b0fd5a8c-5885-4323-9e7e-f88b25cf75e4"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"gitlab-gitlab-runner"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"checksum/configmap":"3317adc0a35207ad1b62079a9da580e3c757b1f31012e15ca737213461aa0fcc","checksum/secrets":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","gitlab.com/prometheus_port":"9252","gitlab.com/prometheus_scrape":"true","kubectl.kubernetes.io/restartedAt":"2025-06-07T15:03:34+09:00"},"creationTimestamp":null,"labels":{"app":"gitlab-gitlab-runner","chart":"gitlab-runner-0.74.1","heritage":"Helm","release":"gitlab"}},"spec":{"containers":[{"command":["/usr/bin/dumb-init","--","/bin/bash","/configmaps/entrypoint"],"env":[{"name":"CI_SERVER_URL","value":"https://gitlab.yoonjin2.kr"},{"name":"RUNNER_EXECUTOR","value":"kubernetes"},{"name":"REGISTER_LOCKED","value":"false"},{"name":"RUNNER_TAG_LIST"},{"name":"KUBERNETES_NAMESPACE","value":"gitlab"},{"name":"SESSION_SERVER_ADDRESS"},{"name":"GIT_SSL_NO_VERIFY","value":"true"},{"name":"CI_SERVER_SKIP_TLS_VERIFY","value":"true"}],"image":"registry.gitlab.com/gitlab-org/gitlab-runner:alpine-v17.9.1","imagePullPolicy":"IfNotPresent","lifecycle":{"preStop":{"exec":{"command":["/entrypoint","unregister","--all-runners"]}}},"livenessProbe":{"exec":{"command":["/bin/bash","/configmaps/check-live","3"]},"failureThreshold":3,"initialDelaySeconds":60,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":4},"name":"gitlab-gitlab-runner","ports":[{"containerPort":9252,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["/usr/bin/pgrep","gitlab.*runner"]},"failureThreshold":3,"initialDelaySeconds":60,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":4},"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/secrets","name":"projected-secrets"},{"mountPath":"/home/gitlab-runner/.gitlab-runner","name":"etc-gitlab-runner"},{"mountPath":"/configmaps","name":"configmaps"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":65533,"runAsUser":100,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccount":"gitlab-gitlab-runner","serviceAccountName":"gitlab-gitlab-runner","terminationGracePeriodSeconds":3600,"volumes":[{"emptyDir":{"medium":"Memory"},"name":"runner-secrets"},{"emptyDir":{"medium":"Memory"},"name":"etc-gitlab-runner"},{"name":"projected-secrets","projected":{"defaultMode":420,"sources":[{"secret":{"name":"gitlab-minio-secret"}},{"secret":{"items":[{"key":"runner-registration-token","path":"runner-registration-token"},{"key":"runner-token","path":"runner-token"}],"name":"gitlab-gitlab-runner-secret"}}]}},{"configMap":{"defaultMode":420,"name":"gitlab-gitlab-runner"},"name":"configmaps"}]}}},"status":{"conditions":[{"lastTransitionTime":"2025-06-07T06:03:34Z","lastUpdateTime":"2025-06-07T06:07:34Z","message":"ReplicaSet \"gitlab-gitlab-runner-6f585b89f6\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2025-06-07T06:07:35Z","lastUpdateTime":"2025-06-07T06:07:35Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":6,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab
  creationTimestamp: "2025-06-06T09:20:55Z"
  generation: 13
  labels:
    app: gitlab-gitlab-runner
    app.kubernetes.io/managed-by: Helm
    chart: gitlab-runner-0.74.1
    heritage: Helm
    release: gitlab
  name: gitlab-gitlab-runner
  namespace: gitlab
  resourceVersion: "198837"
  uid: b0fd5a8c-5885-4323-9e7e-f88b25cf75e4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitlab-gitlab-runner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configmap: 3317adc0a35207ad1b62079a9da580e3c757b1f31012e15ca737213461aa0fcc
        checksum/secrets: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        gitlab.com/prometheus_port: "9252"
        gitlab.com/prometheus_scrape: "true"
        kubectl.kubernetes.io/restartedAt: "2025-06-07T15:29:00+09:00"
      creationTimestamp: null
      labels:
        app: gitlab-gitlab-runner
        chart: gitlab-runner-0.74.1
        heritage: Helm
        release: gitlab
    spec:
      containers:
      - command:
        - /usr/bin/dumb-init
        - --
        - /bin/bash
        - /configmaps/entrypoint
        env:
        - name: CI_SERVER_URL
          value: https://gitlab.yoonjin2.kr
        - name: RUNNER_EXECUTOR
          value: kubernetes
        - name: REGISTER_LOCKED
          value: "false"
        - name: RUNNER_TAG_LIST
        - name: KUBERNETES_NAMESPACE
          value: gitlab
        - name: SESSION_SERVER_ADDRESS
        - name: GIT_SSL_NO_VERIFY
          value: "true"
        - name: CI_SERVER_SKIP_TLS_VERIFY
          value: "true"
        image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine-v17.9.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /entrypoint
              - unregister
              - --all-runners
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /configmaps/check-live
            - "3"
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 4
        name: gitlab-gitlab-runner
        ports:
        - containerPort: 9252
          name: metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - gitlab.*runner
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 4
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: projected-secrets
        - mountPath: /home/gitlab-runner/.gitlab-runner
          name: etc-gitlab-runner
        - mountPath: /configmaps
          name: configmaps
        - mountPath: /home/gitlab-runner/.gitlab-runner/certs/
          name: custom-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65533
        runAsUser: 100
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: gitlab-gitlab-runner
      serviceAccountName: gitlab-gitlab-runner
      terminationGracePeriodSeconds: 3600
      volumes:
      - emptyDir:
          medium: Memory
        name: runner-secrets
      - emptyDir:
          medium: Memory
        name: etc-gitlab-runner
      - name: projected-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: gitlab-minio-secret
          - secret:
              items:
              - key: runner-registration-token
                path: runner-registration-token
              - key: runner-token
                path: runner-token
              name: gitlab-gitlab-runner-secret
      - name: custom-certs
        secret:
          defaultMode: 420
          secretName: gitlab-runner-ca-cert
      - configMap:
          defaultMode: 420
          name: gitlab-gitlab-runner
        name: configmaps
status:
  conditions:
  - lastTransitionTime: "2025-06-07T06:03:34Z"
    lastUpdateTime: "2025-06-07T06:31:11Z"
    message: ReplicaSet "gitlab-gitlab-runner-77b9f66b5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-07T06:31:41Z"
    lastUpdateTime: "2025-06-07T06:31:41Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 13
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
