gitlabUrl: https://your.url
runnerRegistrationToken: "YOUR_TOKEN"
securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  privileged: true
  capabilities:
    drop: ["NET_BIND_SERVICE"]
    add: []

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
certmanager:
  rbac:
    create: true
    rules:
      - apiGroups: ["policy", ""]
        resources: ["podsecuritypolicies", "secrets"]
        verbs:     ["create", "get", "update", "delete", "list", "watch", "use"]
        resourceNames:
          - privileged
serviceAccount:
  create: true
  name: gitlab-ci-admin
