apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-prometheus-server 
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  
  storageClassName: "manual"  

