apiVersion: v1
kind: PersistentVolume
metadata:
  name: default
spec:
  capacity:
    storage: 700Gi  # 스토리지 용량
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # 읽기/쓰기가 가능한 모드
  persistentVolumeReclaimPolicy: Retain  # PVC 삭제 시 PV를 보존
  storageClassName: default  # 로컬 스토리지로 사용할 'StorageClass' 이름
  hostPath:
    path: /data/gitlab  # 로컬 디스크 경로, 실제 디스크 경로로 설정
    type: DirectoryOrCreate  # 디렉토리가 없으면 생성

