apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    [datasources]
      [datasources.loki]
        type = loki
        url = http://10.105.76.8:3100
        editable = true
        org_id = 1
        version = 1
        name = Loki
      [datasources.prometheus]
        type = prometheus
        url = http://10.99.177.54:9090
        editable = true
        org_id = 1
        version = 1
        name = Prometheus
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"grafana.ini":"[analytics]\ncheck_for_updates = true\n[grafana_net]\nurl = https://grafana.net\n[log]\nmode = console\n[paths]\ndata = /var/lib/grafana/\nlogs = /var/log/grafana\nplugins = /var/lib/grafana/plugins\nprovisioning = /etc/grafana/provisioning\n[server]\ndomain = ''\n[datasources]\n  [datasources.loki]\n    type = loki\n    url = http://10.105.76.8:3100\n    editable = true\n    org_id = 1\n    version = 1\n    name = Loki\n  [datasources.prometheus]\n    type = prometheus\n    url = http://10.105.76.8:9090\n    editable = true\n    org_id = 1\n    version = 1\n    name = Prometheus\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"prometheus","meta.helm.sh/release-namespace":"monitoring"},"creationTimestamp":"2025-04-20T13:08:32Z","labels":{"app.kubernetes.io/instance":"prometheus","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"11.6.0","helm.sh/chart":"grafana-8.12.1"},"name":"prometheus-grafana","namespace":"monitoring","resourceVersion":"3837","uid":"85ef6c63-e830-41cd-ad0d-5c8b6be06023"}}
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-04-20T13:08:32Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.6.0
    helm.sh/chart: grafana-8.12.1
  name: prometheus-grafana
  namespace: monitoring
  resourceVersion: "54406"
  uid: 85ef6c63-e830-41cd-ad0d-5c8b6be06023
