loki:
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: loki-storageclass # StorageClass 이름 확인
    accessModes:
      - ReadWriteOnce
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: boltdb-shipper
        object_store:
          config:
            directory: /var/lib/loki/index
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
