- hosts: master
  become: yes
  become_user: "root"
  become_method: sudo
  vars:
    user: "yjlee"
  vars_files:
    - vault.yaml
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: cluster_init_master.log

    - name: Create .kube Directory
      file:
        path: "/home/{{ user }}/.kube"
        state: directory
        mode: 0755

    - name: Copy admin.conf to User's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ user }}/.kube/config"
        remote_src: yes
        owner: "{{ user }}"
    - name: Set ownership on kube config
      ansible.builtin.file:
        path: "/home/{{ user }}/.kube/config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode : "0400"

    - name: Add Cilium Helm Repository
      become: yes
      become_user: "{{ user }}"
      command: helm repo add cilium https://helm.cilium.io/
      args:
        creates: "/home/{{ user }}/.local/share/helm/repositories/cilium-index.yaml"

    - name: Update Helm Repositories
      become: yes
      become_user: "{{ user }}"
      command: helm repo update

    - name: Get kubeadm join command from master
      ansible.builtin.shell: "kubeadm token create --print-join-command"
      register: join_command_result
      run_once: true
      changed_when: false
        
    - name: Store join command
      ansible.builtin.set_fact:
        kube_join_command: "{{ join_command_result.stdout }}"
        run_once: true
