apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-gitlab-redis-master-0 
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  
  storageClassName: "manual"  

